const seedWords = [
  ["Let's try anyway", "anyway", "とにかく"],
  ["Following the speech, we had dinner", "following", "〜の後で"],
  ["Please refer to the map", "refer", "参照する"],
  ["Tickets are available online", "available", "利用できる"],
  ["The sales department", "department", "部門"],
  ["A large conference room", "conference", "会議"],
  ["According to the email", "according to", "〜によると"],
  ["Who most likely is the woman?", "likely", "おそらく"],
  ["What does the man offer to do?", "offer", "申し出る"],
  ["New office equipment", "equipment", "設備"],
  ["Please provide me with your email address", "provide", "提供する"],
  ["Local businesses", "local", "地元の"],
  ["Purchase tickets", "purchase", "購入する"],
  ["A job opening", "opening", "空き"],
  ["Construction project", "construction", "建設"],
  ["While touring the factory", "tour", "見学する"],
  ["Market research", "research", "調査"],
  ["Attend a meeting", "attend", "出席する"],
  ["Change a delivery date", "delivery", "配達"],
  ["I recently bought a printer", "recently", "最近"],
  ["What is indicated about Mr. Cato?", "indicate", "示す"],
  ["An employee of a hotel", "employee", "従業員"],
  ["Request additional staff", "additional", "追加の"],
  ["A customer survey", "survey", "調査"],
  ["Review a report", "review", "見直す"],
  ["The production area", "production", "生産"],
  ["Conveniently located near a subway station", "located", "位置している"],
  ["Details of a plan", "detail", "詳細"],
  ["Announce the winners", "announce", "発表する"],
  ["A computer repair shop", "repair", "修理する"],
  ["An increase in sales", "increase", "増加"],
  ["What is not included in the form?", "include", "含む"],
  ["The item is currently out of stock", "currently", "現在"],
  ["An advertising campaign", "advertising", "広告"],
  ["We charge fifty dollars for the service", "charge", "料金を請求する"],
  ["Mr.Cato is expected to arrive tomorrow", "expect", "予想する"],
  ["A family-owned firm", "firm", "会社"],
  ["Visit a client", "client", "顧客"],
  ["Financial support from the government", "financial", "財政的な"],
  ["An annual report", "annual", "年次の"],
  ["Make an online payment", "payment", "支払い"],
  ["This year's budget", "budget", "予算"],
  ["Fill out an application", "application", "申請"],
  ["Before signing a contract", "contract", "契約"],
  ["A management seminar", "management", "管理"],
  ["An employee's performance", "performance", "業績"],
  ["We are pleased with the final result", "pleased", "満足している"],
  ["Confirm a payment", "confirm", "確認する"],
  ["Awards ceremony", "award", "賞"],
  ["A clothing store", "clothing", "衣類"],
  ["Products on display", "display", "展示する"],
  ["A successful candidate", "candidate", "候補者"],
  ["What is stated about the hotel?", "state", "述べる"],
  ["A museum exhibit", "exhibit", "展示物"],
  ["A Q&A session", "session", "会議"],
  ["Please note that prices may change", "note", "注意する"],
  ["Process an order", "process", "処理する"],
  ["Please read all the instructions", "instruction", "指示"],
  ["Sign up for membership", "membership", "会員資格"],
  ["A travel agency", "agency", "代理店"],
  ["A Seattle-based company", "based", "拠点を置く"],
  ["A research facility", "facility", "施設"],
  ["Advance notice", "advance", "事前の"],
  ["Join a committee", "committee", "委員会"],
  ["The event was successful", "successful", "成功した"],
  ["Excellent service", "excellent", "優れた"],
  ["The fashion industry", "industry", "産業"],
  ["Pay a late fee", "fee", "料金"],
  ["Accept an offer", "accept", "受け入れる"],
  ["Prepare for an upcoming event", "upcoming", "今後の"],
  ["Haruki Murakami's latest novel", "latest", "最新の"],
  ["Submit a report", "submit", "提出する"],
  ["Use public transportation", "transportation", "交通"],
  ["Send a resume", "resume", "履歴書"],
  ["A company executive", "executive", "役員"],
  ["Introduce a new line of products", "introduce", "導入する"],
  ["Have no previous experience", "previous", "以前の"],
  ["Review a proposal", "proposal", "提案"],
  ["Office supplies", "supply", "供給"],
  ["My resume is enclosed", "enclose", "同封する"],
  ["Returns policy", "policy", "方針"],
  ["Register for employee training", "register", "登録する"],
  ["Arrange a meeting", "arrange", "手配する"],
  ["Receive a bill", "bill", "請求書"],
  ["Hire an assistant", "hire", "雇う"],
  ["Approve a plan", "approve", "承認する"],
  ["Conduct a survey", "conduct", "実施する"],
  ["An opportunity to work with you", "opportunity", "機会"],
  ["The deadline for the project", "deadline", "締切"],
  ["A corporate trainer", "corporate", "企業の"],
  ["A three-year warranty", "warranty", "保証"],
  ["Necessary forms", "necessary", "必要な"],
  ["Reserve a room at a hotel", "reserve", "予約する"],
  ["Local residents", "resident", "住民"],
  ["Create a new logo", "create", "作る"],
  ["We are happy to inform you that...", "inform", "知らせる"],
  ["Allow customers to pay online", "allow", "許可する"],
  ["What problem does the man mention?", "mention", "言及する"],
  ["I really appreciate your help", "appreciate", "感謝する"],
  ["Replacement parts", "replacement", "交換"],
  ["Traffic update", "update", "更新"],
  ["Open a new branch", "branch", "支店"],
  ["Paid leave", "paid", "有給の"],
  ["Unfortunately there are some problems", "unfortunately", "残念ながら"],
  ["In original condition", "original", "元の"],
  ["A rent increase", "rent", "家賃"],
  ["Write a memo", "memo", "メモ"],
  ["Shop for luggage", "luggage", "荷物"],
  ["A newspaper editor", "editor", "編集者"],
  ["An art exhibition", "exhibition", "展示会"],
  ["A leading company", "leading", "主要な"],
  ["Lead an organization", "organization", "組織"],
  ["Release a new album", "release", "発売する"],
  ["For a limited time", "limited", "限定の"],
  ["A normal procedure", "procedure", "手順"],
  ["An experienced engineer", "experienced", "経験豊富な"],
  ["All company personnel", "personnel", "人員"],
  ["The author of a popular book", "author", "著者"],
  ["Employee benefits", "benefit", "利益"],
  ["Focus on one point", "focus", "集中する"],
  ["Participate in the workshop", "participate", "参加する"],
  ["The cause of the problem", "cause", "原因"],
  ["A degree in journalism", "degree", "学位"],
  ["Purchase directly from a website", "directly", "直接"],
  ["The host of a television show", "host", "司会者"],
  ["An expert in the field", "expert", "専門家"],
  ["We were impressed by your knowledge", "impress", "感動させる"],
  ["Work mainly in the steel industry", "mainly", "主に"],
  ["Make suggestions", "suggestion", "提案"],
  ["Relationships with suppliers", "supplier", "供給業者"],
  ["An important document", "document", "書類"],
  ["Remind employees about the policy", "remind", "思い出させる"],
  ["Workers are required to wear uniforms", "require", "要求する"],
  ["A sales representative", "representative", "代表者"],
  ["The packaging area", "packaging", "包装"],
  ["A job description", "description", "説明"],
  ["A property manager", "property", "不動産"],
  ["Call me at extension four six four nine", "extension", "内線"],
  ["Inquire about a job", "inquire", "問い合わせる"],
  ["Display merchandise", "merchandise", "商品"],
  ["A highly successful business", "highly", "非常に"],
  ["The campaign resulted in success", "result", "結果"],
  ["Thank you for your assistance", "assistance", "支援"],
  ["Employees are encouraged to attend the event", "encourage", "促す"],
  ["Each individual in the company", "individual", "個人"],
  ["When entering the laboratory", "laboratory", "研究室"],
  ["Consider working in Japan", "consider", "検討する"],
  ["Move the headquarters to Boston", "headquarters", "本社"],
  ["We are ready to ship your order", "ship", "発送する"],
  ["Commercial buildings", "commercial", "商業の"],
  ["A medical device", "device", "装置"],
  ["For whom is the notice intended?", "intended", "意図された"],
  ["A product brochure", "brochure", "パンフレット"],
  ["By express mail", "mail", "郵便"],
  ["I prefer to work part-time", "prefer", "好む"],
  ["I'm writing in response to your letter", "response", "返答"],
  ["Companies in the region", "region", "地域"],
  ["Donations to a museum", "donation", "寄付"],
  ["The third quarter", "quarter", "四半期"],
  ["A rental agreement", "agreement", "合意"],
  ["A scientific journal", "journal", "雑誌"],
  ["Distribute a document", "distribute", "配布する"],
  ["Potential customers", "potential", "潜在的な"],
  ["Reschedule an appointment", "reschedule", "日程変更する"],
  ["Renew a contract", "renew", "更新する"],
  ["Ship from a warehouse", "warehouse", "倉庫"],
  ["A full refund", "refund", "返金"],
  ["What are listeners advised to do?", "advise", "助言する"],
  ["The tickets sold out immediately", "immediately", "すぐに"],
  ["The city council", "council", "議会"],
  ["The program is usually broadcast on Saturdays", "broadcast", "放送する"],
  ["I am responsible for training employees", "responsible", "責任がある"],
  ["Avoid wasting time", "avoid", "避ける"],
  ["Effective advertising campaigns", "effective", "効果的な"],
  ["Receive an invitation", "invitation", "招待"],
  ["Reduce prices", "reduce", "減らす"],
  ["Park a vehicle", "vehicle", "乗り物"],
  ["Efficient use of energy", "efficient", "効率的な"],
  ["A car manufacturer", "manufacturer", "製造業者"],
  ["Comfortable rooms and friendly staff", "comfortable", "快適な"],
  ["The correct address", "correct", "正しい"],
  ["Downtown restaurants", "downtown", "中心街"],
  ["The method of payment", "method", "方法"],
  ["The entire staff", "entire", "全体の"],
  ["A wide range of services", "range", "範囲"],
  ["A hotel in a beautiful setting", "setting", "環境"],
  ["We apologize for the inconvenience", "apologize", "謝罪する"],
  ["Frequent use of the internet", "frequent", "頻繁な"],
  ["Texas promotion to sales manager", "promotion", "昇進"],
  ["Regarding your order", "regarding", "〜に関して"],
  ["Temporary workers", "temporary", "一時的な"],
  ["Traditional Italian dishes", "traditional", "伝統的な"],
  ["Admission is free for all members", "admission", "入場"],
  ["The room can fit fifty people", "fit", "収容できる"],
  ["Contact a reference", "reference", "推薦人"],
  ["Shipment status", "status", "状況"],
  ["Fuel costs", "fuel", "燃料"],
  ["Nearly two years", "nearly", "ほぼ"],
  ["Meet in the cafeteria for lunch", "cafeteria", "食堂"],
  ["Determine how to sell the product", "determine", "決定する"],
  ["Travel expenses", "expense", "費用"],
  ["Overseas markets", "overseas", "海外の"],
  ["I am fully satisfied with the service", "satisfied", "満足した"],
  ["Where would the article most likely appear?", "appear", "現れる"],
  ["Develop a plan", "develop", "発展させる"],
  ["Improve customer service", "improve", "改善する"],
  ["A reasonable price", "reasonable", "妥当な"],
  ["What is the man unable to do?", "unable", "できない"],
  ["All flights have been delayed", "delay", "遅延"],
  ["Legal advice", "legal", "法的な"],
  ["Under the regulations", "regulation", "規則"],
  ["Our business is expanding", "expand", "拡大する"],
  ["The launch of a new product", "launch", "開始"],
  ["A letter of recommendation", "recommendation", "推薦"],
  ["Please direct any questions to me", "direct", "向ける"],
  ["Increase profits", "profit", "利益"],
  ["Seek interns for the summer", "seek", "求める"],
  ["The winning entry", "entry", "応募"],
  ["File a claim", "claim", "請求"],
  ["A repair crew", "crew", "作業員"],
  ["Meet demand", "demand", "需要"],
  ["Sales figures", "figure", "数字"],
  ["Raise money for charity", "raise", "上げる"],
  ["I have attached my resume", "attach", "添付する"],
  ["A way of attracting customers", "attract", "引きつける"],
  ["Health insurance for employees", "insurance", "保険"],
  ["The scheduled departure date", "departure", "出発"],
  ["The mayor of Tex Town", "mayor", "市長"],
  ["An account balance", "balance", "残高"],
  ["An estimate for the project", "estimate", "見積もり"],
  ["a commercial district", "district", "地区"],
  ["A former employee", "former", "以前の"],
  ["design", "設計"],
  ["A modern building", "modern", "現代的な"],
  ["Tips on packing", "tip", "助言"],
  ["Establish a business", "establish", "設立する"],
  ["An option to change the date", "option", "選択肢"],
  ["Retire after twenty years of service", "retire", "退職する"],
  ["The search for the next president", "search", "探索"],
  ["A specific example", "specific", "具体的な"],
  ["Agricultural technology", "agricultural", "農業の"],
  ["historical figures", "historical", "歴史的な"],
  ["I hope you find this information helpful", "helpful", "役立つ"],
  ["Complaints about the noise", "complaint", "苦情"],
  ["Experience in a related field", "related", "関連した"],
  ["Simply fill out the form below", "simply", "単に"],
  ["Offer a unique opportunity", "unique", "独自の"],
  ["Any questions concerning the order", "concerning", "〜に関して"],
  ["A well-deserved reputation", "reputation", "評判"],
  ["Ability to speak three languages", "ability", "能力"],
  ["The time of arrival", "arrival", "到着"],
  ["I am familiar with the area", "familiar", "よく知っている"],
  ["An ideal location", "ideal", "理想的な"],
  ["Maintain a website", "maintain", "維持する"],
  ["A landscaping company", "landscaping", "造園"],
  ["Organize an event", "organize", "整理する"],
  ["A significant increase in profits", "significant", "重要な"],
  ["A special occasion", "occasion", "機会"],
  ["Safety standards", "standard", "基準"],
  ["An impressive educational background", "background", "経歴"],
  ["A guided tour", "guided", "案内付きの"],
  ["Advanced technology", "advanced", "高度な"],
  ["An alternative date", "alternative", "代替の"],
  ["I'm confident that I can do it", "confident", "自信がある"],
  ["Over the past two decades", "decade", "10年間"],
  ["Attend the initial training session", "initial", "最初の"],
  ["My order arrived in two separate shipments", "separate", "別々の"],
  ["The grand opening celebration", "celebration", "祝賀"],
  ["Express concern", "concern", "懸念"],
  ["Work environment", "environment", "環境"],
  ["Operate a machine safely", "operate", "操作する"],
  ["Various designs and patterns", "various", "さまざまな"],
  ["A brief report", "brief", "簡潔な"],
  ["Full-time employees", "full-time", "フルタイムの"],
  ["The overall budget", "overall", "全体の"],
  ["Achieve a sales target", "achieve", "達成する"],
  ["Pay on a monthly basis", "basis", "基準"],
  ["A sports complex", "complex", "複合施設"],
  ["We are delighted to see you", "delighted", "喜んでいる"],
  ["Obtain information from the internet", "obtain", "得る"],
  ["Honor an employee", "honor", "称える"],
  ["Properly trained staff", "properly", "適切に"],
  ["Suitable for outdoor use", "suitable", "適した"],
  ["Personal electronic devices", "electronic", "電子の"],
  ["Finalize a contract", "finalize", "最終決定する"],
  ["A generous donation to a charity", "generous", "気前のよい"],
  ["In preparation for an event", "preparation", "準備"],
  ["Main duties of a teacher", "duty", "義務"],
  ["Earn the respect of people", "earn", "得る"],
  ["I am willing to work overseas", "willing", "進んで〜する"],
  ["The book is worth reading", "worth", "価値がある"],
  ["A project funded by the government", "fund", "資金"],
  ["Free overnight delivery", "overnight", "翌日配達の"],
  ["Particularly interested in history", "particularly", "特に"],
  ["Every aspect of a project", "aspect", "側面"],
  ["Please do not hesitate to contact us", "hesitate", "ためらう"],
  ["I was not involved with the project", "involved", "関与した"],
  ["A regularly updated list", "regularly", "定期的に"],
  ["Apply for a scholarship", "scholarship", "奨学金"],
  ["The meeting will begin shortly", "shortly", "まもなく"],
  ["Automobile manufacturing", "automobile", "自動車"],
  ["A security deposit", "deposit", "保証金"],
  ["The book contains useful information", "contain", "含む"],
  ["The contents of the book", "content", "内容"],
  ["Proof of purchase", "proof", "証拠"],
  ["Affect the price", "affect", "影響する"],
  ["Our products are recognized for their quality", "recognize", "認める"],
  ["Represent a company", "represent", "代表する"],
  ["Tex was transferred to Alaska", "transfer", "異動させる"],
  ["Celebrate the 20th anniversary", "anniversary", "記念日"],
  ["The machine will automatically shut down", "automatically", "自動的に"],
  ["Production capacity", "capacity", "能力"],
  ["Travel destinations", "destination", "目的地"],
  ["Obtain a grant", "grant", "助成金"],
  ["Publish a magazine", "publish", "出版する"],
  ["The book is accompanied by a CD", "accompany", "添える"],
  ["Economic growth", "economic", "経済の"],
  ["Check extremely carefully", "extremely", "非常に"],
  ["A financial institution", "institution", "機関"],
  ["Accurate sales figures", "accurate", "正確な"],
  ["Compete with large companies", "compete", "競争する"],
  ["Emphasize a point", "emphasize", "強調する"],
  ["I was aware of the problem", "aware", "気づいている"],
  ["The town is crowded with tourists", "crowded", "混雑した"],
  ["The team was praised by the CEO", "praise", "称賛する"],
  ["A valuable addition to the team", "valuable", "価値ある"],
  ["Explore the possibility", "explore", "探る"],
  ["Found a company", "found", "設立する"],
  ["Basic functions", "function", "機能"],
  ["Have a negative impact on the environment", "impact", "影響"],
  ["An amazing success", "amazing", "驚くべき"],
  ["Assure Tex that he will be promoted", "assure", "保証する"],
  ["Thank you for your cooperation", "cooperation", "協力"],
  ["A rise in popularity", "popularity", "人気"],
  ["A construction permit", "permit", "許可証"],
  ["Solve a problem", "solve", "解決する"],
  ["Vote against a proposal", "vote", "投票する"],
  ["Locally grown crops", "crop", "作物"],
  ["There are no hotels in this neighborhood", "neighborhood", "近所"],
  ["The permanent exhibit", "permanent", "常設の"],
  ["We regret to inform you that", "regret", "残念に思う"],
  ["Slightly increased from twenty-four to twenty-seven percent", "slightly", "わずかに"],
  ["The system is very complicated", "complicated", "複雑な"],
  ["Various factors", "factor", "要因"],
  ["Favorable customer reviews", "favorable", "好意的な"],
  ["Guarantee same-day delivery", "guarantee", "保証する"],
  ["Due to mechanical trouble", "mechanical", "機械の"],
  ["A high priority", "priority", "優先事項"],
  ["Relatively recent trend", "relatively", "比較的"],
  ["Water is an important natural resource", "resource", "資源"],
  ["Free shuttle service", "shuttle", "シャトル"],
  ["The catalog is divided into three sections", "divide", "分ける"],
  ["A singer native to the town", "native", "生まれつきの"],
  ["We can't afford to do that", "afford", "余裕がある"],
  ["High income", "income", "収入"],
  ["Damage occurred during shipment", "occur", "起こる"],
  ["Significant savings", "saving", "節約"],
  ["Research findings", "findings", "調査結果"],
  ["I was unable to locate the book", "locate", "見つける"],
  ["Postpone a meeting", "postpone", "延期する"],
  ["Preserve the environment", "preserve", "保護する"],
  ["Prove to be difficult", "prove", "証明する"],
  ["I can't remember the exact date", "exact", "正確な"],
  ["Gain popularity", "gain", "得る"],
  ["Labor costs", "labor", "労働"],
  ["Be widely regarded as", "regard", "見なす"],
  ["Work closely with local businesses", "closely", "密接に"],
  ["Deserve a promotion", "deserve", "値する"],
  ["Identify problems", "identify", "特定する"],
  ["Loyal customers", "loyal", "忠実な"],
  ["The most promising applicant", "promising", "有望な"],
  ["Stress the importance of reading", "stress", "強調する"],
  ["Analyze customer feedback", "analyze", "分析する"],
  ["The report was commissioned by Tex Corporation", "commission", "依頼する"],
  ["We are committed to providing quality service", "committed", "献身的な"],
  ["A cost comparison", "comparison", "比較"],
  ["Electronic components", "component", "構成要素"],
  ["Enable staff to work from home", "enable", "可能にする"],
  ["An enjoyable stay at a hotel", "enjoyable", "楽しい"],
  ["Existing customers", "existing", "既存の"],
  ["Post a flyer", "flyer", "チラシ"],
  ["Proceed to the boarding gate", "proceed", "進む"],
  ["Tex prevented us from entering the room", "prevent", "防ぐ"],
  ["Teachers and students alike", "alike", "同様に"],
  ["I was appointed chairperson of the committee", "appoint", "任命する"],
  ["A high-speed internet connection", "connection", "接続"],
  ["I am eager to learn new things", "eager", "熱心な"],
  ["Ease of use", "ease", "容易さ"],
  ["Fairly common", "fairly", "かなり"],
  ["Absolutely free of charge", "absolutely", "絶対に"],
  ["A warm atmosphere", "atmosphere", "雰囲気"],
  ["Calculate delivery costs", "calculate", "計算する"],
  ["In contrast to last year", "contrast", "対照"],
  ["Monitor the quality of products", "monitor", "監視する"],
  ["I occasionally travel abroad", "occasionally", "時々"],
  ["Practical experience", "practical", "実用的な"],
  ["A serious problem", "serious", "深刻な"],
  ["The strength of materials", "strength", "強さ"],
  ["Equally important", "equally", "同様に"],
  ["Imports from China", "import", "輸入"],
  ["An informal survey", "informal", "非公式の"],
  ["They're facing each other", "face", "向き合う"],
  ["A man is wearing headphones", "wear", "身に着ける"],
  ["A man is pointing at a screen", "point", "指さす"],
  ["The shelves are full of books", "shelf", "棚"],
  ["A man is standing on a ladder", "ladder", "はしご"],
  ["A man is trimming some bushes", "trim", "刈り込む"],
  ["A woman is examining a document", "examine", "調べる"],
  ["They are greeting each other", "greet", "あいさつする"],
  ["A man is sweeping the floor", "sweep", "掃く"],
  ["He's adjusting some equipment", "adjust", "調整する"],
  ["Some people are heading toward a plane", "head", "向かう"],
  ["She's handling some luggage", "handle", "扱う"],
  ["A ladder is leaning against a building", "lean", "寄りかかる"],
  ["A woman is paying a cashier", "cashier", "レジ係"],
  ["The floor is being polished", "polish", "磨く"],
  ["A man is holding a lid open", "lid", "ふた"],
  ["A woman is sitting on a stool", "stool", "スツール"],
  ["They are walking on a crosswalk", "crosswalk", "横断歩道"],
  ["He's working beside a brick wall", "brick", "れんが"],
  ["Some pictures are hanging on the wall", "hang", "掛かる"],
  ["A man is kneeling on the floor", "kneel", "ひざまずく"],
  ["A woman is sewing an item", "sew", "縫う"],
  ["Ladders are propped up against a wall", "be propped up against", "立てかけられている"],
  ["A man is standing on a walkway", "walkway", "通路"],
  ["They're walking side by side", "side by side", "並んで"],
  ["Some people are applauding the presenter", "applaud", "拍手する"],
  ["A woman is watering some plants", "water", "水をやる"],
  ["A woman is fastening an apron", "fasten", "留める"],
  ["There are some boxes in the hallway", "hallway", "廊下"],
  ["The man is using a microscope", "microscope", "顕微鏡"],
  ["Some paintings are mounted on a wall", "mount", "取り付ける"],
  ["A band is performing for the audience", "audience", "観客"],
  ["Some people are walking through a plaza", "plaza", "広場"],
  ["A woman is wearing gloves", "glove", "手袋"],
  ["Printers have been placed against the wall", "place", "置く"],
  ["A woman is wearing protective clothing", "protective", "保護用の"],
  ["Some papers are scattered on a table", "scattered", "散らばった"],
  ["People are gathered near an artwork", "artwork", "芸術作品"],
  ["A ladder is casting a shadow", "cast a shadow", "影を落とす"],
  ["He's paging through reading material", "page through", "ページをめくる"],
  ["Cars are parked in a row", "row", "列"],
  ["She's reaching into her bag", "reach", "手を伸ばす"],
  ["Diners are seated inside", "diner", "食事客"],
  ["A woman is pouring some juice", "pour", "注ぐ"],
  ["They are loading some boxes onto the truck", "load", "積み込む"],
  ["Passengers are boarding a train", "board", "乗り込む"],
  ["There are pots on the table", "pot", "鍋"],
  ["He's walking by a garbage can", "garbage can", "ごみ箱"],
  ["Some dishes are stacked on a table", "stack", "積み重ねる"],
  ["She's opening a drawer", "drawer", "引き出し"],
  ["He's playing an instrument", "instrument", "楽器"],
  ["She's removing a book from her handbag", "remove", "取り出す"],
  ["They're loading some cargo onto a ship", "cargo", "貨物"],
  ["Some people are seated in an auditorium", "auditorium", "講堂"],
  ["He's leaning on a railing", "railing", "手すり"],
  ["Potted plants have been arranged in rows", "potted plant", "鉢植え"],
  ["A desk is positioned between chairs", "position", "位置づける"],
  ["People are browsing some items", "browse", "見て回る"],
  ["Buildings are reflected in the water", "reflect", "反射する"],
  ["A map is laid out on the table", "lay out", "広げる"],
  ["They're talking near a doorway", "doorway", "出入口"],
  ["She's wheeling a cart", "wheel", "押して進める"],
  ["Some steps lead to a building", "lead to", "〜へ続く"],
  ["They are sitting opposite each other", "sit opposite", "向かい合って座る"],
  ["There are some mountains in the distance", "in the distance", "遠くに"],
  ["A man is mowing the lawn", "mow", "芝を刈る"],
  ["The vase is filled with flowers", "vase", "花瓶"],
  ["A fountain is spraying water", "fountain", "噴水"],
  ["Some people are waiting at the intersection", "intersection", "交差点"],
  ["There are some chairs on the platform", "platform", "プラットホーム"],
  ["Some boats are tied to the dock", "dock", "波止場"],
  ["He's glancing at a magazine", "glance", "ちらりと見る"],
  ["There are some dishes in the cupboard", "cupboard", "戸棚"],
  ["A woman is exiting a vehicle", "exit", "出る"],
  ["Some people are sitting at their workstations", "workstation", "作業席"],
  ["He is gazing out the window", "gaze", "見つめる"],
  ["A car is parked at a curb", "curb", "縁石"],
  ["The roof of the house is slanted", "slanted", "傾いた"],
  ["A man is climbing a staircase", "staircase", "階段"],
  ["There are spectators in the stadium", "spectator", "観客"],
  ["A woman is standing in a courtyard", "courtyard", "中庭"],
  ["Some pottery is being displayed", "pottery", "陶器"],
  ["Some cookware is arranged on the counter", "cookware", "調理器具"],
  ["High-rise buildings overlook the water", "overlook", "見渡す"],
  ["A boat is sailing past a pier", "pier", "桟橋"],
  ["Some people are gathered near a lighthouse", "lighthouse", "灯台"],
  ["A man is drawing a portrait", "portrait", "肖像画"],
  ["The reception desk is unattended", "unattended", "無人の"],
  ["Some people are standing under an awning", "awning", "ひさし"],
  ["A patio overlooks a river", "patio", "中庭テラス"],
  ["The chairs are unoccupied", "unoccupied", "空いている"],
  ["Pedestrians are crossing the street", "pedestrian", "歩行者"],
  ["Some crates are being transported", "crate", "木箱"],
  ["She's arranging utensils on a table", "utensil", "食器類"],
  ["Some people are stationed at a counter", "station", "配置する"],
  ["Workers are cleaning the windowpanes", "windowpane", "窓ガラス"],
  ["She's strolling along the shore", "stroll", "散歩する"],
  ["Some lampposts line the street", "lamppost", "街灯"],
  ["A man is pushing a wheelbarrow", "wheelbarrow", "手押し車"],
  ["a canopy is shading some merchandise", "canopy", "天蓋"],
  ["refrigerator", "冷蔵庫"],
  ["microwave oven", "電子レンジ"],
  ["stove", "コンロ"],
  ["air conditioner", "エアコン"],
  ["heater", "暖房器具"],
  ["vacuum cleaner", "掃除機"],
  ["washing machine", "洗濯機"],
  ["light bulb", "電球"],
  ["bookcase", "本棚"],
  ["bookshelf", "本棚"],
  ["laundry detergent", "洗濯用洗剤"],
  ["light fixture", "照明器具"],
  ["stapler", "ホチキス"],
  ["sunscreen", "日焼け止め"],
  ["envelope", "封筒"],
  ["scale cupboard", "はかり／戸棚"],
  ["scissors", "はさみ"],
  ["stationery", "文房具"],
  ["plastic bag", "ビニール袋"],
  ["folding chair", "折りたたみ椅子"],
  ["cardboard box", "段ボール箱"],
  ["rug", "じゅうたん"],
  ["drape", "カーテン"],
  ["scarf", "スカーフ"],
  ["laptop", "ノートパソコン"],
  ["mobile phone", "携帯電話"],
  ["cell phone", "携帯電話"],
  ["photocopier", "コピー機"],
  ["copy machine", "コピー機"],
  ["rechargeable battery", "充電式電池"],
  ["briefcase", "ブリーフケース"],
  ["revolving door", "回転ドア"],
  ["freight elevator", "貨物用エレベーター"],
  ["treadmill", "トレッドミル"],
  ["I haven't seen Tex lately", "lately", "最近"],
  ["Why did you choose this profession?", "profession", "職業"],
  ["Permission from a supervisor", "supervisor", "上司"],
  ["Ensure that the products are safe", "ensure", "確実にする"],
  ["Hundreds of submissions from readers", "submission", "提出物"],
  ["Notify employees of the change", "notify", "通知する"],
  ["I definitely need the item", "definitely", "間違いなく"],
  ["Employees are eligible to receive paid holidays", "eligible", "資格がある"],
  ["All the paperwork is ready", "paperwork", "書類仕事"],
  ["A complimentary breakfast", "complimentary", "無料の"],
  ["Revise a plan", "revise", "修正する"],
  ["Track an order", "track", "追跡する"],
  ["An administrative assistant", "administrative", "事務の"],
  ["Retail stores", "retail", "小売り"],
  ["Reduce inventory", "inventory", "在庫"],
  ["Extensive analysis", "extensive", "広範な"],
  ["Promotional materials", "promotional", "販促用の"],
  ["Catering service", "catering", "ケータリング"],
  ["A wildlife photographer", "wildlife", "野生生物"],
  ["I have been assigned the work", "assign", "割り当てる"],
  ["What is implied about the hotel?", "imply", "ほのめかす"],
  ["I am looking forward to the banquet", "banquet", "宴会"],
  ["Valid until the end of May", "valid", "有効な"],
  ["Provide quality service at affordable prices", "affordable", "手頃な"],
  ["A newly renovated library", "renovate", "改装する"],
  ["Follow industry guidelines", "guidelines", "指針"],
  ["A copy of the certificate", "certificate", "証明書"],
  ["An innovative technology", "innovative", "革新的な"],
  ["The first item on the agenda", "agenda", "議題"],
  ["Assembly line workers", "assembly", "組立"],
  ["Install a new printer", "install", "設置する"],
  ["New employee orientation", "orientation", "オリエンテーション"],
  ["A renowned scientist", "renowned", "高名な"],
  ["Appropriate clothes for a job interview", "appropriate", "適切な"],
  ["Use fresh ingredients", "ingredient", "材料"],
  ["A storage facility", "storage", "保管"],
  ["Serve food and beverages to guests", "beverage", "飲み物"],
  ["Prior to the meeting", "prior", "〜より前に"],
  ["The upcoming merger with Tex Corporation", "merger", "合併"],
  ["A seaside inn", "inn", "宿"],
  ["Each room is equipped with internet access", "equip", "備え付ける"],
  ["A brief summary", "summary", "要約"],
  ["A two-year lease", "lease", "賃貸契約"],
  ["Return a defective product", "defective", "欠陥のある"],
  ["A quarterly magazine", "quarterly", "四半期ごとの"],
  ["An extended warranty", "extended", "延長された"],
  ["A famous architect", "architect", "建築家"],
  ["A local grocery store", "grocery", "食料品店"],
  ["A sculpture exhibition", "sculpture", "彫刻"],
  ["Send an itinerary", "itinerary", "旅程表"],
  ["The company directory", "directory", "名簿"],
  ["My driver's license expires in April", "expire", "期限が切れる"],
  ["Negotiate with vendors", "vendor", "販売業者"],
  ["Talk with a colleague", "colleague", "同僚"],
  ["library patrons", "patron", "利用者"],
  ["Relocate an office", "relocate", "移転する"],
  ["Tourism industry", "tourism", "観光"],
  ["My office is being remodeled", "remodel", "改装する"],
  ["Consumer reports", "consumer", "消費者"],
  ["Inspect a building", "inspect", "点検する"],
  ["I have eaten at numerous local restaurants", "numerous", "多数の"],
  ["A new payroll system", "payroll", "給与支払い"],
  ["I am qualified for the position", "qualified", "資格のある"],
  ["Kitchen appliances", "appliance", "家電製品"],
  ["Excellent service and competitive prices", "competitive", "競争力のある"],
  ["The company specializes in web design", "specialize", "専門とする"],
  ["Fill out a questionnaire", "questionnaire", "アンケート"],
  ["Approximately two hours", "approximately", "およそ"],
  ["Contribute to a team", "contribute", "貢献する"],
  ["Improve productivity", "productivity", "生産性"],
  ["The meeting starts promptly at 1pm", "promptly", "迅速に"],
  ["A marketing strategy", "strategy", "戦略"],
  ["Experienced and dedicated staff", "dedicated", "献身的な"],
  ["Exceptional customer service", "exceptional", "並外れた"],
  ["Hold a luncheon", "luncheon", "昼食会"],
  ["Exceed expectations", "exceed", "上回る"],
  ["Operate in multiple countries", "multiple", "複数の"],
  ["The regulations clearly specify that", "specify", "明記する"],
  ["A convention venue", "venue", "会場"],
  ["Household products", "household", "家庭用の"],
  ["Evaluate a product", "evaluate", "評価する"],
  ["Negotiate with a client", "negotiate", "交渉する"],
  ["Make a booking", "booking", "予約"],
  ["A daily circulation of 30,000", "circulation", "発行部数"],
  ["The completion of the project", "completion", "完了"],
  ["Relevant work experience", "relevant", "関連する"],
  ["A thorough review", "thorough", "徹底的な"],
  ["Fly to Seattle via Denver", "via", "〜経由で"],
  ["Relationships in the workplace", "workplace", "職場"],
  ["The price includes flights and accommodations", "accommodations", "宿泊施設"],
  ["Flexible work hours", "flexible", "柔軟な"],
  ["Some experts predict that...", "predict", "予測する"],
  ["Seat and meal preferences", "preference", "好み"],
  ["Reduce costs by a substantial amount", "substantial", "かなりの"],
  ["Easily accessible by train", "accessible", "利用しやすい"],
  ["Media coverage", "coverage", "報道"],
  ["Generate profits", "generate", "生み出す"],
  ["Refreshments will be served", "refreshment", "軽食"],
  ["A reliable secretary", "reliable", "信頼できる"],
  ["Advertising revenue", "revenue", "収益"],
  ["The fundraising dinner", "fundraising", "資金調達"],
  ["An accomplished designer", "accomplished", "熟練した"],
  ["Acquire a company", "acquire", "取得する"],
  ["The weather is cold, so dress accordingly", "accordingly", "それに応じて"],
  ["Positive reviews from critics", "critic", "評論家"],
  ["Highlight differences", "highlight", "強調する"],
  ["Profile a businessperson", "profile", "紹介記事"],
  ["Motivate employees", "motivate", "やる気にさせる"],
  ["A magazine subscription", "subscription", "購読"],
  ["Encounter a serious problem", "encounter", "遭遇する"],
  ["A luxury sedan", "luxury", "高級な"],
  ["Street parking is prohibited in this area", "prohibit", "禁止する"],
  ["The problem was resolved", "resolve", "解決する"],
  ["Telephone service was restored this morning", "restore", "回復させる"],
  ["Surrounding areas", "surrounding", "周辺の"],
  ["Alert techs to the problem", "alert", "警告する"],
  ["The highly anticipated new book", "anticipated", "期待される"],
  ["Consistently rank among the top ten universities", "consistently", "一貫して"],
  ["Fat-free dairy products", "dairy", "乳製品"],
  ["The first phase", "phase", "段階"],
  ["Edit a manuscript", "manuscript", "原稿"],
  ["Work a lot of overtime", "overtime", "残業"],
  ["On the premises", "premises", "敷地内"],
  ["The rent includes all utilities", "utility", "公共料金"],
  ["A laundry room", "laundry", "洗濯室"],
  ["I am enthusiastic about the project", "enthusiastic", "熱心な"],
  ["Outline a policy", "outline", "概要を示す"],
  ["A packet of materials", "packet", "一式資料"],
  ["Retain a receipt", "retain", "保持する"],
  ["Make sure you have all your belongings", "belongings", "持ち物"],
  ["Energy conservation", "conservation", "保全"],
  ["Routine maintenance work", "routine", "定期的な"],
  ["Live in urban areas", "urban", "都市の"],
  ["Fifty percent of the workforce", "workforce", "労働力"],
  ["A brief biography of the author", "biography", "伝記"],
  ["The company has recently changed ownership", "ownership", "所有権"],
  ["A pastry chef", "pastry", "ペストリー"],
  ["Both building managers and tenants", "tenant", "借家人"],
  ["Reduce the workload", "workload", "仕事量"],
  ["Sufficient time", "sufficient", "十分な"],
  ["Main characteristics of the product", "characteristic", "特徴"],
  ["A combined effort", "combined", "共同の"],
  ["The event will conclude with a concert", "conclude", "締めくくる"],
  ["Costs associated with buying a house", "associate", "関連づける"],
  ["Because of a scheduling conflict", "conflict", "衝突"],
  ["Real estate investment", "investment", "投資"],
  ["See a physician", "physician", "医師"],
  ["As a token of our appreciation for", "token", "しるし"],
  ["A partial refund", "partial", "一部の"],
  ["Resume operations", "resume", "履歴書"],
  ["Car dealerships", "dealership", "販売店"],
  ["The garment is made of cotton", "garment", "衣服"],
  ["Security measures were implemented", "implement", "実施する"],
  ["Receive a paycheck", "paycheck", "給料"],
  ["Recruit new staff", "recruit", "募集する"],
  ["Substitute new for old", "substitute", "置き換える"],
  ["our tours typically take an hour", "typically", "通常は"],
  ["An authorized dealer", "authorize", "認可する"],
  ["More expensive than comparable products", "comparable", "同等の"],
  ["A faculty member at Tex  College", "faculty", "教員"],
  ["A growth initiative", "initiative", "取り組み"],
  ["Postage is calculated by weight", "postage", "郵便料金"],
  ["The author will sign books afterwards", "afterwards", "その後"],
  ["Aim to cut energy use", "aim", "目指す"],
  ["The film received generally positive reviews", "generally", "一般的に"],
  ["The room is occupied", "occupied", "使用中の"],
  ["A solid reputation", "solid", "確かな"],
  ["Tex's attempt to become a singer", "attempt", "試み"],
  ["The person in authority", "authority", "権威者"],
  ["The domestic market", "domestic", "国内の"],
  ["Without permission", "permission", "許可"],
  ["A strong presence in the area", "presence", "存在感"],
  ["A rapidly growing company", "rapidly", "急速に"],
  ["Provide relief to consumers", "relief", "救済"],
  ["Reward employees for their hard work", "reward", "報いる"],
  ["Translate English into Japanese", "translate", "翻訳する"],
  ["Under any circumstances", "circumstance", "状況"],
  ["Contrary to expectations", "contrary", "反対の"],
  ["Mr. Cato was eventually promoted to CEO", "eventually", "最終的に"],
  ["Be directly exposed to the sun", "expose", "さらす"],
  ["A panel of experts", "panel", "委員団"],
  ["The bottom portion of the ticket", "portion", "部分"],
  ["Primary duties", "primary", "主な"],
  ["Opening remarks", "remark", "発言"],
  ["In a timely manner", "timely", "適時の"],
  ["The most commonly used methods", "commonly", "一般的に"],
  ["Consult a doctor", "consult", "相談する"],
  ["Convert a warehouse into an office", "convert", "変える"],
  ["You have no obligation to do so", "obligation", "義務"],
  ["Resign without notice", "resign", "辞職する"],
  ["The door is securely locked", "securely", "しっかりと"],
  ["Strive to cut costs", "strive", "努力する"],
  ["A timeline of events", "timeline", "予定表"],
  ["Urge Tex to change his mind", "urge", "強く勧める"],
  ["Acknowledge receipt of the order", "acknowledge", "受領を認める"],
  ["A diverse group of experts", "diverse", "多様な"],
  ["A bank transaction", "transaction", "取引"],
  ["A lack of information", "lack", "不足"],
  ["Customer satisfaction is essential to us", "essential", "不可欠な"],
  ["The majority of employees", "majority", "大多数"],
  ["Observe a trend", "observe", "観察する"],
  ["Possess knowledge", "possess", "所有する"],
  ["Sales rose sharply", "sharply", "急激に"],
  ["Make adjustments to the plan", "adjustment", "調整"],
  ["I prefer an aisle seat", "aisle", "通路"],
  ["Photographs capture memorable moments in life", "capture", "捉える"],
  ["The committee consists of five members", "consist", "成る"],
  ["Teaching experience is desirable", "desirable", "望ましい"],
  ["A heavily used bus route", "heavily", "激しく"],
  ["Investigate a possibility", "investigate", "調査する"],
  ["Take the measurements of a table", "measurement", "測定"],
  ["An urgent request", "urgent", "緊急の"],
  ["The checkout counter", "checkout", "会計カウンター"],
  ["Dispose of garbage", "dispose", "処分する"],
  ["Modify a contract", "modify", "修正する"],
  ["Open an outlet in Japan", "outlet", "店舗"],
  ["Ask for a prescription", "prescription", "処方箋"],
  ["Situated downtown, the hotel is convenient", "situated", "位置している"],
  ["Surprisingly Tex passed the exam", "surprisingly", "驚くほど"],
  ["Transform a train station into a museum", "transform", "変える"],
  ["Undergo major renovations", "undergo", "経験する"],
  ["The blueprints for the new theater", "blueprint", "設計図"],
  ["Boost the company's profit", "boost", "押し上げる"],
  ["Considerably lower prices", "considerably", "かなり"],
  ["Eliminate a risk", "eliminate", "排除する"],
  ["Available exclusively to our members", "exclusively", "限定して"],
  ["The pipe under the sink is leaking", "leak", "漏れる"],
  ["Preliminary results from a survey", "preliminary", "予備的な"],
  ["A sophisticated design", "sophisticated", "洗練された"],
  ["The most recent statistics", "statistics", "統計"],
  ["A vacant unit in an apartment building", "vacant", "空室の"],
  ["Evidence of payment", "evidence", "証拠"],
  ["A shopping excursion", "excursion", "小旅行"],
  ["Influence a decision", "influence", "影響を与える"],
  ["Live in an ordinary house", "ordinary", "普通の"],
  ["Reject a proposal", "reject", "拒否する"],
  ["Tailor services to clients' needs", "tailor", "合わせる"],
  ["Assume responsibilities", "assume", "引き受ける"],
  ["A previous engagement", "engagement", "先約"],
  ["Achieve international fame", "fame", "名声"],
  ["A modest increase in price", "modest", "控えめな"],
  ["Apply for a patent", "patent", "特許"],
  ["The company is pursuing a new market", "pursue", "追求する"],
  ["A remote mountain village", "remote", "遠隔の"],
  ["Reveal the cause of the problem", "reveal", "明らかにする"],
  ["A housing allowance", "allowance", "手当"],
  ["Innovation is crucial for business success", "crucial", "極めて重要な"],
  ["A distinguished career as a journalist", "distinguished", "著名な"],
  ["I'm sorry to disturb you", "disturb", "邪魔する"],
  ["Applicants must be fluent in Mandarin", "fluent", "流暢な"],
  ["Fulfill requirements", "fulfill", "満たす"],
  ["The objective of the survey", "objective", "目的"],
  ["Restrict employees from accessing the Internet", "restrict", "制限する"],
  ["Sales have been increasing steadily", "steadily", "着実に"],
  ["An adequate explanation", "adequate", "十分な"],
  ["The assessment of the value", "assessment", "評価"],
  ["Mr. Kato attributes his success to luck", "attribute", "〜のせいにする"],
  ["Prepare an agenda beforehand", "beforehand", "前もって"],
  ["A challenging task", "challenging", "やりがいのある"],
  ["Good luck in your future endeavors", "endeavor", "努力"],
  ["An inspiring speech", "inspiring", "感動的な"],
  ["Make remarkable progress", "remarkable", "著しい"],
  ["Take safety measures", "measure", "対策"],
  ["The company is struggling to survive", "struggle", "苦闘する"],
  ["The wage level", "wage", "賃金"],
  ["Adapt to a new work environment", "adapt", "適応する"],
  ["Set an ambitious goal", "ambitious", "意欲的な"],
  ["I am capable of doing the job", "capable", "能力がある"],
  ["Have serious consequences", "consequence", "結果"],
  ["Impose a fee on customers", "impose", "課す"],
  ["The former and the latter", "latter", "後者"],
  ["The daily output of a factory", "output", "生産高"],
  ["Proudly announce", "proudly", "誇らしげに"],
  ["A stable supply of electricity", "stable", "安定した"],
  ["The transition from school to work", "transition", "移行"],
  ["Without written consent", "consent", "同意"],
  ["Produce dependable cars and trucks", "dependable", "信頼できる"],
  ["Mr. Catto is a diligent worker", "diligent", "勤勉な"],
  ["Illustrate a point", "illustrate", "説明する"],
  ["Work independently and as a team member", "independently", "独立して"],
  ["The company's mission", "mission", "使命"],
  ["Moderate exercise", "moderate", "適度な"],
  ["The sales outlook", "outlook", "見通し"],
  ["Rapidly and precisely", "precisely", "正確に"],
  ["A concentrated effort", "concentrated", "集中的な"],
  ["The hotel has ample parking", "ample", "十分な"],
  ["An asset to the team", "asset", "資産"],
  ["A controversial issue", "controversial", "物議を醸す"],
  ["Disappointing sales", "disappointing", "期待外れの"],
  ["Tex was instrumental in the project", "instrumental", "重要な役割を果たす"],
  ["Without interruption", "interruption", "中断"],
  ["From a broad perspective", "perspective", "観点"],
  ["The scope of the study", "scope", "範囲"],
  ["Speculation from industry experts", "speculation", "推測"],
  ["Supplement income by writing books", "supplement", "補う"],
  ["We are really understaffed", "understaffed", "人手不足の"],
  ["The CEO rarely appears in public", "rarely", "めったに〜ない"],
  ["Use caution", "caution", "注意"],
  ["Legislation to limit the use of drones", "legislation", "法律"],
  ["A logical choice", "logical", "論理的な"],
  ["board of directors", "取締役会"],
  ["accounting department", "経理部"],
  ["marketing department", "マーケティング部"],
  ["human resources department", "人事部"],
  ["personnel department", "人事部"],
  ["administrative department", "管理部"],
  ["legal department", "法務部"],
  ["sales department", "営業部"],
  ["technology department", "技術部"],
  ["security department", "警備部"],
  ["purchasing department", "購買部"],
  ["payroll department", "給与部"],
  ["public relations department", "広報部"],
  ["advertising department", "広告部"],
  ["general affairs department", "総務部"],
  ["plumber mechanic", "配管工／整備士"],
  ["carpenter", "大工"],
  ["welder", "溶接工"],
  ["electrician", "電気技師"],
  ["civil engineer", "土木技師"],
  ["dentist surgeon", "歯科医／外科医"],
  ["pharmacist", "薬剤師"],
  ["veterinarian", "獣医"],
  ["bakery", "パン屋"],
  ["florist", "花屋"],
  ["cleaners", "クリーニング店"],
  ["locksmith", "鍵屋"],
  ["moving company", "引っ越し業者"],
  ["hardware store", "金物店"],
  ["printer", "印刷業者"],
  ["courier", "宅配業者"],
  ["real estate agency", "不動産会社"],
  ["accountant", "会計士"],
  ["auditor", "監査人"],
  ["anthropologist", "人類学者"],
  ["biologist", "生物学者"],
  ["botanist", "植物学者"],
  ["scientist", "科学者"],
  ["chemist", "化学者"],
  ["historian lawyer", "歴史家／弁護士"],
  ["attorney", "弁護士"],
  ["professor", "教授"],
  ["paralegal", "法律補助職"],
  ["journalist announcer", "記者／アナウンサー"],
  ["host", "司会者"],
  ["correspondent", "特派員"],
  ["editor", "編集者"],
  ["proofreader", "校正者"],
  ["novelist librarian", "小説家／司書"],
  ["flight attendant", "客室乗務員"],
  ["travel agent", "旅行代理店"],
  ["tour guide", "ツアーガイド"],
  ["concierge", "コンシェルジュ"],
  ["housekeeping", "清掃係"],
  ["conductor", "車掌"],
  ["operator", "オペレーター"],
  ["architect", "建築家"],
  ["photographer choreographer", "写真家／振付師"],
  ["actor", "俳優"],
  ["actress", "女優"],
  ["curator", "学芸員"],
  ["receptionist", "受付係"],
  ["secretary", "秘書"],
  ["spokesperson", "広報担当者"],
  ["ambassador", "大使"],
  ["security guard", "警備員"],
  ["cashier", "レジ係"],
  ["accounting architecture", "会計学／建築学"],
  ["astronomy", "天文学"],
  ["biology", "生物学"],
  ["chemistry", "化学"],
  ["ecology", "生態学"],
  ["economics", "経済学"],
  ["education", "教育学"],
  ["engineering", "工学"],
  ["fine arts", "美術"],
  ["history", "歴史"],
  ["journalism", "ジャーナリズム"],
  ["law", "法学"],
  ["linguistics literature", "言語学／文学"],
  ["mathematics", "数学"],
  ["medicine", "医学"],
  ["philosophy", "哲学"],
  ["physics", "物理学"],
  ["psychology", "心理学"],
  ["robotics", "ロボット工学"],
  ["sociology", "社会学"],
  ["due to", "〜のために"],
  ["owing to", "〜のために"],
  ["despite", "〜にもかかわらず"],
  ["in spite of", "〜にもかかわらず"],
  ["notwithstanding", "〜にもかかわらず"],
  ["given", "〜を考えると"],
  ["in light of", "〜を考慮して"],
  ["in the event of", "〜の場合には"],
  ["in addition to", "〜に加えて"],
  ["except for", "〜を除いて"],
  ["regardless of", "〜に関係なく"],
  ["instead of", "〜の代わりに"],
  ["whereas", "一方で"],
  ["whether", "〜かどうか"],
  ["as soon as", "〜するとすぐに"],
  ["once", "いったん〜すれば"],
  ["unless", "〜でない限り"],
  ["now that", "今や〜なので"],
  ["so that", "〜するために"],
  ["in order that", "〜するように"],
  ["although", "〜だけれども"],
  ["though", "〜だけれども"],
  ["even though", "〜にもかかわらず"],
  ["even if", "たとえ〜でも"],
  ["provided that", "〜という条件で"],
  ["as long as", "〜する限り"],
  ["in case", "〜に備えて"],
  ["given that", "〜を踏まえると"],
  ["in the event that", "もし〜なら"],
  ["insofar as", "〜する限りで"],
  ["inasmuch as", "〜なので"],
  ["therefore", "それゆえ"],
  ["however", "しかし"],
  ["nevertheless", "それにもかかわらず"],
  ["moreover", "そのうえ"],
  ["furthermore", "さらに"],
  ["consequently", "その結果"],
  ["thereby", "それによって"],
  ["thus", "したがって"],
  ["meanwhile", "その間に"],
  ["A lumber business", "lumber", "木材"],
  ["The reverse side", "reverse", "裏側"],
  ["Attendance is voluntary", "voluntary", "任意の"],
  ["A construction contractor", "contractor", "請負業者"],
  ["The company has an on-site childcare center", "on-site", "現場の／施設内の"],
  ["A comprehensive list of products", "comprehensive", "包括的な"],
  ["Confidential documents", "confidential", "機密の"],
  ["Expertise in computer programming", "expertise", "専門知識"],
  ["One of Tokyo's premier restaurants", "premier", "一流の"],
  ["A souvenir shop", "souvenir", "土産物"],
  ["Rafting trips", "rafting", "ラフティング"],
  ["In the overhead compartment", "compartment", "区画"],
  ["Check fabric samples", "fabric", "布地"],
  ["A spacious room", "spacious", "広々とした"],
  ["Make upgrades to the air conditioning system", "upgrade", "改良する"],
  ["Showcase new products", "showcase", "披露する"],
  ["A commuter train", "commuter", "通勤者用の"],
  ["Enhance customer service", "enhance", "高める"],
  ["Use a freight elevator", "freight", "貨物"],
  ["Nominate a colleague for an award", "nominate", "推薦する"],
  ["A discontinued appliance", "discontinued", "生産中止の"],
  ["A mentoring program", "mentoring", "指導制度"],
  ["Personalized service", "personalized", "個別対応の"],
  ["Work at a pharmacy", "pharmacy", "薬局"],
  ["An excerpt from a meeting", "excerpt", "抜粋"],
  ["Publicize a book", "publicize", "公表する"],
  ["Pay tuition fees", "tuition", "授業料"],
  ["In compliance with regulations", "compliance", "順守"],
  ["Clarify the situation", "clarify", "明確にする"],
  ["The municipal government", "municipal", "市の"],
  ["Tex and Masaya 16 and 18 respectively", "respectively", "それぞれ"],
  ["Affordable yet durable", "durable", "耐久性のある"],
  ["The tower is the town's landmark", "landmark", "名所"],
  ["Please include your portfolio", "portfolio", "作品集"],
  ["Recipients of the prize", "recipient", "受取人"],
  ["A prototype of an aircraft", "prototype", "試作品"],
  ["Damage in transit", "transit", "輸送中"],
  ["Verify an account", "verify", "確認する"],
  ["Experience at a managerial level", "managerial", "管理職の"],
  ["Culinary institute", "culinary", "料理の"],
  ["Formal attire is required in the office", "attire", "服装"],
  ["Reimburse travel expenses", "reimburse", "払い戻す"],
  ["The staff was courteous", "courteous", "礼儀正しい"],
  ["A fully furnished apartment", "furnished", "家具付きの"],
  ["Highly knowledgeable about investments", "knowledgeable", "知識が豊富な"],
  ["Artists and craftspeople", "craftspeople", "職人たち"],
  ["Delete unnecessary files", "delete", "削除する"],
  ["Emerging markets", "emerging", "新興の"],
  ["Enroll in an aerobics class", "enroll", "登録する"],
  ["Proficiency in English", "proficiency", "熟達"],
  ["Take the scenic route", "scenic", "景色の良い"],
  ["State-of-the-art equipment", "state-of-the-art", "最先端の"],
  ["French cuisine", "cuisine", "料理"],
  ["A critically acclaimed movie", "acclaimed", "高く評価された"],
  ["A certified building inspector", "certified", "認定された"],
  ["Cold medication", "medication", "薬"],
  ["Give an overview", "overview", "概要"],
  ["Heat-resistant glass", "resistant", "耐〜性のある"],
  ["Give a superb presentation", "superb", "素晴らしい"],
  ["An array of books", "array", "多数"],
  ["An informative seminar", "informative", "情報豊富な"],
  ["Nationwide delivery", "nationwide", "全国的な"],
  ["Outdated TOEIC books", "outdated", "時代遅れの"],
  ["A shareholders meeting", "shareholder", "株主"],
  ["A travel voucher", "voucher", "引換券"],
  ["The restaurant adjacent to the hotel", "adjacent", "隣接した"],
  ["In the previous correspondence", "correspondence", "やり取り"],
  ["Liquid detergent", "detergent", "洗剤"],
  ["For the duration of the event", "duration", "期間"],
  ["The machine is still functional", "functional", "機能する"],
  ["Hands-on training", "hands-on", "実地の"],
  ["A three-day intensive training seminar", "intensive", "集中的な"],
  ["A last-minute change", "last-minute", "直前の"],
  ["I'm thrilled to see you", "thrilled", "わくわくした"],
  ["A spectacular sunset", "spectacular", "壮観な"],
  ["A young entrepreneur", "entrepreneur", "起業家"],
  ["An introductory course", "introductory", "入門の"],
  ["Minimize costs and maximize profits", "minimize", "最小限にする"],
  ["A prestigious award", "prestigious", "名声のある"],
  ["A screening of a film", "screening", "上映"],
  ["Amenities such as gyms and swimming pools", "amenity", "快適設備"],
  ["A lengthy process", "lengthy", "長い"],
  ["You will be compensated for the damage", "compensate", "補償する"],
  ["I have misplaced my phone", "misplace", "置き忘れる"],
  ["A notable feature", "notable", "注目すべき"],
  ["A subsidiary of a Japanese company", "subsidiary", "子会社"],
  ["Authentic works of art", "authentic", "本物の"],
  ["A designated parking area", "designated", "指定された"],
  ["Cause disruption to traffic", "disruption", "混乱"],
  ["Fragile items", "fragile", "壊れやすい"],
  ["An ongoing project", "ongoing", "進行中の"],
  ["Publish a periodical", "periodical", "定期刊行物"],
  ["Call a plumber", "plumber", "配管工"],
  ["Incur a fine", "incur", "被る"],
  ["Oversee a department", "oversee", "監督する"],
  ["Retrieve the data", "retrieve", "取り戻す"],
  ["Attend a class reunion", "reunion", "同窓会"],
  ["A rigorous testing process", "rigorous", "厳格な"],
  ["Specifications for the project", "specification", "仕様"],
  ["A tentative schedule", "tentative", "暫定的な"],
  ["An online tutorial", "tutorial", "解説講座"],
  ["An apprentice technician", "apprentice", "見習い"],
  ["Make a bid", "bid", "入札"],
  ["Discard old papers", "discard", "捨てる"],
  ["Family outings", "outing", "外出"],
  ["An overwhelmingly positive response", "overwhelmingly", "圧倒的に"],
  ["The proceeds will go to charity", "proceeds", "収益"],
  ["Please refrain from using mobile phones", "refrain", "控える"],
  ["Inclement weather", "inclement", "荒天の"],
  ["Novice cooks", "novice", "初心者"],
  ["Activate a credit card", "activate", "有効化する"],
  ["Personal anecdotes", "anecdote", "逸話"],
  ["Work in collaboration with others", "collaboration", "協力"],
  ["Commemorate an anniversary", "commemorate", "記念する"],
  ["A duplicate key", "duplicate", "複製"],
  ["During the intermission", "intermission", "休憩時間"],
  ["Recycle food waste to make fertilizer", "fertilizer", "肥料"],
  ["Proofread an article", "proofread", "校正する"],
  ["Solicit donations", "solicit", "募る"],
  ["Unveil a new product", "unveil", "発表する"],
  ["The rule is applicable to all employees", "applicable", "適用できる"],
  ["A letter to commend an employee", "commend", "称賛する"],
  ["The dessert complements the main dish", "complement", "引き立てる"],
  ["Offer incentives to customers", "incentive", "奨励策"],
  ["Incorporate exercise into everyday life", "incorporate", "取り入れる"],
  ["Don't let your membership lapse", "lapse", "失効する"],
  ["A picturesque village", "picturesque", "絵のように美しい"],
  ["Prospective customers", "prospective", "見込みのある"],
  ["Simplify a system", "simplify", "簡素化する"],
  ["Surpass last year's sales", "surpass", "上回る"],
  ["Surplus promotional materials", "surplus", "余剰の"],
  ["Withstand high temperatures", "withstand", "耐える"],
  ["An advocate for energy efficiency", "advocate", "提唱者"],
  ["An aspiring writer", "aspiring", "志望している"],
  ["Assorted fruits and vegetables", "assorted", "いろいろな"],
  ["Excellent credentials as a scientist", "credentials", "資格・実績"],
  ["Interoffice mail", "interoffice", "社内の"],
  ["A machine malfunction", "malfunction", "故障"],
  ["A mutually beneficial relationship", "mutually", "相互に"],
  ["Check the website periodically", "periodically", "定期的に"],
  ["Copyright law", "copyright", "著作権"],
  ["Affordable and nutritious dishes", "nutritious", "栄養価の高い"],
  ["Obstruct the view", "obstruct", "妨げる"],
  ["Abundant opportunities for career advancement", "abundant", "豊富な"],
  ["The weather in Auckland is quite agreeable", "agreeable", "快適な"],
  ["Reach a compromise", "compromise", "妥協"],
  ["Continuous improvement of quality", "continuous", "継続的な"],
  ["A dominant position in the market", "dominant", "支配的な"],
  ["I was exhausted", "exhausted", "疲れ果てた"],
  ["Fierce competition", "fierce", "激しい"],
  ["a prosperous town", "prosperous", "繁栄した"],
  ["The original quote", "quote", "引用"],
  ["What is the man reluctant to do?", "reluctant", "気が進まない"],
  ["A remedy for slow sales", "remedy", "改善策"],
  ["Be solely responsible for the decision", "solely", "単独で"],
  ["Good communication is vital in the workplace", "vital", "不可欠な"],
  ["Revitalize a community", "revitalize", "活性化する"],
  ["Construction will commence in September", "commence", "開始する"],
  ["Countless times", "countless", "無数の"],
  ["Devise a method", "devise", "考案する"],
  ["Execute a plan", "execute", "実行する"],
  ["Foster a good work environment", "foster", "育む"],
  ["Initiate a negotiation", "initiate", "開始する"],
  ["Insight into the cause of the problem", "insight", "洞察"],
  ["The advertisement was misleading", "misleading", "誤解を招く"],
  ["As a precaution", "precaution", "予防策"],
  ["Transparent glass", "transparent", "透明な"],
  ["The event coincides with my birthday", "coincide", "一致する"],
  ["The report was clear and concise", "concise", "簡潔な"],
  ["A delegation of engineers from Japan", "delegation", "代表団"],
  ["Receive a medical diagnosis", "diagnosis", "診断"],
  ["Enforce a new policy", "enforce", "施行する"],
  ["Prove a hypothesis", "hypothesis", "仮説"],
  ["Different from the predecessor", "predecessor", "前任者"],
  ["Prominently displayed in a magazine", "prominently", "目立つように"],
  ["Adoption of a new method", "adoption", "採用"],
  ["Accelerate growth", "accelerate", "加速する"],
  ["Adhere to a procedure", "adhere", "従う"],
  ["Allocate sufficient funds for a project", "allocate", "割り当てる"],
  ["An appraisal of a house", "appraisal", "査定"],
  ["Compile a list of participants", "compile", "まとめる"],
  ["Conform to international standards", "conform", "適合する"],
  ["Due to time constraints", "constraint", "制約"],
  ["Minimize distractions at work", "distraction", "気を散らすもの"],
  ["Facilitate a discussion", "facilitate", "促進する"],
  ["The Internet is integral to our lives", "integral", "不可欠な"],
  ["Interact with colleagues", "interact", "交流する"],
  ["My persistence paid off", "persistence", "粘り強さ"],
  ["A sales quota", "quota", "ノルマ"],
  ["The parking lot was too congested", "congested", "混雑した"],
  ["Deduct tax from payments", "deduct", "差し引く"],
  ["Embrace an idea", "embrace", "受け入れる"],
  ["Synthetic materials", "synthetic", "合成の"],
  ["Terminate a contract", "terminate", "終了する"],
  ["Detect an error", "detect", "見つける"],
  ["Patiently answer questions", "patiently", "辛抱強く"],
  ["A male-female ratio of one to five", "ratio", "比率"],
  ["Dietary restrictions", "dietary", "食事に関する"],
  ["Intentionally delay payments", "intentionally", "意図的に"],
  ["Give a persuasive speech", "persuasive", "説得力のある"],
  ["Accommodate a request", "accommodate", "対応する"],
  ["Open a bank account", "account", "口座／説明する"],
  ["Address a problem", "address", "対処する／話しかける／住所を書く"],
  ["Steve's last public appearance", "appearance", "外見／登場"],
  ["Apply for the position", "apply", "応募する／塗る／適用される"],
  ["A doctor's appointment", "appointment", "予約／任命"],
  ["A magazine article", "article", "記事"],
  ["A battery of tests", "battery", "一連"],
  ["The board of directors met yesterday", "board", "乗り込む"],
  ["Book a room", "book", "予約する"],
  ["We do not carry that item", "carry", "扱う／運ぶ"],
  ["By a certain time", "certain", "一定の"],
  ["The work is nearly complete", "complete", "完了する／完全な"],
  ["Under consideration", "consideration", "考慮"],
  ["One free copy of the book", "copy", "複写／一冊"],
  ["The local media covered the event", "cover", "報道する／覆う／含む"],
  ["Most employees were critical of the plan", "critical", "批判的な／重要な"],
  ["Decline to respond", "decline", "断る／減少する"],
  ["A dictionary definition", "definition", "定義"],
  ["Deliver a product", "deliver", "届ける／述べる"],
  ["Demonstrate how to use the system", "demonstrate", "実演する／示す"],
  ["Research and development", "development", "発展／開発"],
  ["Directions to the museum", "direction", "方向"],
  ["A drawing for prizes", "drawing", "抽選／絵"],
  ["A due date", "due", "期限の／当然の"],
  ["The edge of the water", "edge", "端"],
  ["Express appreciation", "express", "表現する／速達の"],
  ["Extend a deadline", "extend", "延長する／差し伸べる"],
  ["Bus fare,", "fare", "運賃／料理"],
  ["In a timely fashion,", "fashion", "方法／流行"],
  ["The item is featured in the advertisement", "feature", "特徴／特集する"],
  ["In the field of art", "field", "分野／野原"],
  ["Pay a ten dollar fine", "fine", "罰金"],
  ["I look forward to hearing from you", "forward", "前へ／転送する"],
  ["A woman is holding a book", "hold", "持つ／開催する"],
  ["The facility houses six laboratories", "house", "収容する"],
  ["The input data", "input", "入力／意見"],
  ["What are the listeners invited to do?", "invite", "招待する"],
  ["Issue a comment", "issue", "問題／号／発行する"],
  ["The last 10 years", "last", "続く／最後の"],
  ["The lead engineer", "lead", "主導する／導く"],
  ["Leave a message", "leave", "残す／去る／休暇"],
  ["I can manage it alone", "manage", "管理する／なんとかやる"],
  ["Look at the picture marked number one", "mark", "印／評価／記念する"],
  ["Few companies can match our quality service", "match", "一致する／匹敵する"],
  ["Meet requirements", "meet", "満たす／会う"],
  ["Review the minutes", "minute", "議事録"],
  ["Object to a plan", "object", "反対する／物体"],
  ["Once Tex arrives, we will leave", "once", "いったん〜すれば"],
  ["In descending order", "order", "順序／注文"],
  ["An otherwise impossible task", "otherwise", "さもなければ"],
  ["An outgoing person", "outgoing", "社交的な／退任する"],
  ["Outstanding service", "outstanding", "優れた／未払いの"],
  ["Book a table for a party of five", "party", "当事者／パーティー"],
  ["Some plants have been placed in pots", "plant", "植物／工場"],
  ["Post office", "post", "掲示する／配置する"],
  ["Common business practice", "practice", "慣行／練習する"],
  ["Practice a unique method", "australia", "オーストラリア"],
  ["Present an award", "present", "贈呈する／現在の／出席している"],
  ["All our products are produced locally", "produce", "生産する／農産物"],
  ["Professional advice", "professional", "専門的な"],
  ["Project that sales will increase", "project", "予測する／投影する"],
  ["Tex was promoted to general manager", "promote", "昇進させる／促進する"],
  ["At the rate of twenty percent a year", "rate", "割合／評価する"],
  ["You can reach me by email", "reach", "手を伸ばす"],
  ["Tokyo early in the morning", "reach", "手を伸ばす"],
  ["I can't recall his name", "recall", "思い出す／回収"],
  ["The reception will take place next week", "reception", "受付／歓迎会／受信"],
  ["Replace the batteries", "replace", "交換する"],
  ["Make reservations", "reservation", "予約／不安"],
  ["Run a company", "run", "経営する／掲載する／上演される"],
  ["Sample local food", "sample", "試す／見本"],
  ["Secure access to the information", "secure", "確保する／固定する"],
  ["A highly sensitive camera", "sensitive", "敏感な"],
  ["To better serve our customers", "serve", "提供する／務める"],
  ["The copy machine has been serviced", "service", "点検する／サービス"],
  ["I need your signature on this form", "signature", "署名／看板料理"],
  ["Find a solution", "solution", "解決策／溶液"],
  ["Tex Kato stars in the film", "star", "主演する"],
  ["A monthly statement", "statement", "明細書／声明"],
  ["A steep slope", "steep", "急な／高額な"],
  ["Prices are subject to change", "subject", "主題／〜次第で"],
  ["Suggest a change", "suggest", "示唆する／提案する"],
  ["Suspend production", "suspend", "停止する／吊るす"],
  ["A table of contents", "table", "表"],
  ["In terms of price", "terms", "条件／観点／専門用語"],
  ["What's your view on the subject?", "view", "見解"],
  ["Parts weighing more than five kilograms", "weigh", "重さを量る／比較する"],
  ["Withdraw a product from the market", "withdraw", "引き出す／撤回する"],
  ["Of all the works in the museum", "work", "作品"],
  ["The subsequent years", "subsequent", "その後の"],
  ["An abridged version", "abridged", "要約版の"],
  ["Encourage employees to carpool", "carpool", "相乗りする"],
  ["The software is compatible with your computer", "compatible", "互換性のある"],
  ["This product is endorsed by celebrities", "endorse", "支持する"],
  ["Keenly aware of the risks", "keenly", "鋭く／熱心に"],
  ["A commemorative plaque", "plaque", "記念銘板"],
  ["Dilute paint with water", "dilute", "薄める"],
  ["Members are exempt from the fee", "exempt", "免除された"],
  ["Flower centerpieces", "centerpiece", "中心的存在"],
  ["It's an oversight on our part", "oversight", "見落とし"],
  ["We are privileged to work with you", "privileged", "光栄に思う／特権のある"],
  ["Prevent a problem from recurring", "recur", "再発する"],
  ["Skeptical about the possibility", "skeptical", "懐疑的な"],
  ["Sustainable energy", "sustainable", "持続可能な"],
  ["Ancient  Egyptian artifacts", "artifact", "工芸品／遺物"],
  ["Keynote address", "keynote", "基調講演"],
  ["The room offers a breathtaking view", "breathtaking", "息をのむような"],
  ["Work in a cubicle", "cubicle", "小部屋型作業スペース"],
  ["A power outage", "outage", "停止／停電"],
  ["Perishable food items", "perishable", "腐りやすい"],
  ["An avid reader", "avid", "熱心な"],
  ["Take a detour", "detour", "迂回路"],
  ["Expedite a process", "expedite", "迅速化する"],
  ["In the vicinity of the station", "vicinity", "近辺"],
  ["Affiliated companies", "affiliated", "提携した"],
  ["A definitive TOEIC vocabulary book", "definitive", "決定版の"],
  ["Demolish a building", "demolish", "取り壊す"],
  ["a feasible plan", "feasible", "実行可能な"],
  ["The inaugural issue of a magazine", "inaugural", "創刊の／就任の"],
  ["Pay in monthly installments", "installment", "分割払い"],
  ["Gift cards are redeemable for merchandise only", "redeemable", "引き換え可能な"],
  ["Streamline the process", "streamline", "合理化する"],
  ["Everything arrived intact", "intact", "無傷の"],
  ["The occupancy rate of hotels", "occupancy", "稼働率"],
  ["Staff turnover", "turnover", "離職率／売上高"],
  ["Unanimous approval", "unanimous", "全会一致の"],
  ["Road conditions will deteriorate", "deteriorate", "悪化する"],
  ["The table looks sturdy", "sturdy", "頑丈な"],
  ["Adverse health effects", "adverse", "悪影響の"],
  ["The bearer of this coupon", "bearer", "持参人"],
  ["Rising for an unprecedented eight months", "unprecedented", "前例のない"],
  ["Botanical gardens", "botanical", "植物の"],
  ["Salary will be commensurate with experience", "commensurate", "相応の"],
  ["For the third consecutive year", "consecutive", "連続した"],
  ["After long deliberation", "deliberation", "熟慮"],
  ["Behave discreetly", "discreetly", "控えめに"],
  ["The position entails a lot of travel", "entail", "伴う"],
  ["Temperature fluctuations", "fluctuation", "変動"],
  ["One of the foremost law firms", "foremost", "第一級の"],
  ["It is imperative that we act now", "imperative", "極めて重要な"],
  ["Attend a mandatory meeting", "mandatory", "義務的な"],
  ["A meticulously created artwork", "meticulously", "細心に"],
  ["A community outreach program", "outreach", "地域支援"],
  ["During my two-year tenure", "tenure", "在職期間"],
  ["A versatile person", "versatile", "多才な"],
  ["Alleviate traffic congestion", "alleviate", "軽減する"],
  ["An exemplary employee", "exemplary", "模範的な"],
  ["A gala dinner", "gala", "祝賀会"],
  ["Restore a mural", "mural", "壁画"],
  ["The proprietor of a clothing shop", "proprietor", "経営者"],
  ["A stagnant market", "stagnant", "停滞した"],
  ["Stringent quality standards", "stringent", "厳しい"],
  ["Testimonials from customers", "testimonial", "推薦文"],
  ["The turnout for the concert", "turnout", "参加者数"],
  ["We will waive the shipping charge", "waive", "免除する"],
  ["Install a new faucet", "faucet", "蛇口"],
  ["Make amendments to the contract", "amendment", "修正"],
  ["An anonymous donor", "anonymous", "匿名の"],
  ["Report potential fraud", "fraud", "詐欺"],
  ["Tex was held liable for the damage", "liable", "責任がある"],
  ["Be considerate of other people's feelings", "considerate", "思いやりのある"],
  ["Consolidate two divisions into one", "consolidate", "統合する"],
  ["A vigorous campaign", "vigorous", "活発な"],
  ["Plan a company retreat", "retreat", "研修旅行／撤退"],
  ["A custodian at a resort", "custodian", "管理人"],
  ["Forge a relationship", "forge", "築く"],
  ["The impending change in leadership", "impending", "差し迫った"],
  ["Itemize travel expenses", "itemize", "項目別に記す"],
  ["A liaison between management and employees", "liaison", "連絡役"],
  ["The guest found the noise objectionable", "objectionable", "不快な"],
  ["Repave a driveway", "repave", "舗装し直す"],
  ["Address shortcomings", "shortcoming", "欠点"],
  ["A financially viable option", "viable", "実現可能な"],
  ["Sports memorabilia such as balls and photos", "memorabilia", "記念品"],
  ["Deplete the budget", "deplete", "使い果たす"],
  ["The company is in jeopardy", "jeopardy", "危機"],
  ["For a nominal fee", "nominal", "名目上の／わずかな"],
  ["Deviate from the original plan", "deviate", "逸脱する"],
  ["Forfeit the deposit", "forfeit", "失う／没収される"],
  ["Bolster sales", "bolster", "強化する"],
  ["Achieve optimal performance", "optimal", "最適な"],
  ["A purveyor of groceries", "purveyor", "供給業者"],
  ["Sell raffle tickets", "raffle", "くじ"],
  ["Poor ventilation", "ventilation", "換気"],
  ["Through your unwavering efforts", "unwavering", "揺るぎない"],
  ["Your vocabulary has grown exponentially", "exponentially", "指数関数的に"],
  ["a course of action", "行動方針"],
  ["a number of", "いくつかの"],
  ["a wealth of", "豊富な"],
  ["above all", "何よりも"],
  ["after all", "結局"],
  ["ahead of schedule", "予定より早く"],
  ["along with", "〜と一緒に"],
  ["among other things", "とりわけ"],
  ["as a whole", "全体として"],
  ["as early as", "早ければ"],
  ["as far as", "〜する限り"],
  ["as of", "〜の時点で"],
  ["aside from", "〜は別として"],
  ["at all times", "常に"],
  ["at least", "少なくとも"],
  ["at the latest", "遅くとも"],
  ["at your earliest convenience", "できるだけ早く"],
  ["be credited with", "〜の功績があるとされる"],
  ["be supposed to do", "〜することになっている"],
  ["behind schedule", "予定より遅れて"],
  ["box office", "興行収入"],
  ["bulk order", "大量注文"],
  ["by a wide margin", "大差で"],
  ["by any chance", "ひょっとして"],
  ["by means of", "〜によって"],
  ["can you do me a favor?", "お願いできますか"],
  ["come up with", "思いつく"],
  ["cordially invite", "謹んで招待する"],
  ["deal with", "対処する"],
  ["depend on", "〜次第である"],
  ["drop off", "立ち寄る／減少する"],
  ["either is fine", "どちらでも大丈夫"],
  ["field trip", "校外学習"],
  ["figure out", "理解する"],
  ["fill out", "記入する"],
  ["for further information", "詳細については"],
  ["for instance", "例えば"],
  ["get in touch with", "連絡を取る"],
  ["has/have yet to do", "まだ〜していない"],
  ["in a rush", "急いで"],
  ["in a timely manner", "タイムリーに"],
  ["in accordance with", "〜に従って"],
  ["in an effort to do", "〜しようとして"],
  ["in charge of", "担当して"],
  ["in fact", "実際には"],
  ["in for a treat", "楽しいことが待っている"],
  ["in keeping with", "〜に沿って"],
  ["in person", "直接"],
  ["in short", "要するに"],
  ["in progress", "進行中で"],
  ["in the long run", "長い目で見れば"],
  ["in the meantime", "その間に"],
  ["in the process of", "〜の途中で"],
  ["in time for", "〜に間に合って"],
  ["in writing", "書面で"],
  ["instead of", "〜の代わりに"],
  ["it has come to our attention that", "〜ということが判明しました"],
  ["job fair", "就職説明会"],
  ["keep in mind that", "〜を心に留めておく"],
  ["keep up with", "遅れずについていく"],
  ["live up to", "期待に応える"],
  ["look no further than", "〜を見れば十分だ"],
  ["look to do", "〜しようと考える"],
  ["lost and found", "遺失物取扱所"],
  ["make room for", "〜の場所を空ける"],
  ["make sense", "筋が通る"],
  ["narrow down", "絞り込む"],
  ["no later than", "遅くとも〜までに"],
  ["no longer", "もはや〜ない"],
  ["not only a but b as well", "AだけでなくBも"],
  ["null and void", "無効の"],
  ["on a budget", "予算内で"],
  ["on a first-come, first-served basis", "先着順で"],
  ["on average", "平均して"],
  ["on behalf of", "〜を代表して"],
  ["on one's way to", "〜へ向かう途中で"],
  ["on such short notice", "こんな急な知らせで"],
  ["on time", "時間どおりに"],
  ["open to the public", "一般公開の"],
  ["out of order", "故障中で"],
  ["out of paper", "紙切れで"],
  ["out of place", "場違いで"],
  ["out of print", "絶版で"],
  ["out of service", "運休中で"],
  ["out of shape", "体調が悪い／なまっている"],
  ["out of stock", "在庫切れで"],
  ["out of town", "不在で"],
  ["parking lot", "駐車場"],
  ["pass up the opportunity", "機会を逃す"],
  ["pay off", "報われる／完済する"],
  ["plenty of", "たくさんの"],
  ["press conference", "記者会見"],
  ["press release", "プレスリリース"],
  ["quite a few", "かなり多くの"],
  ["rather than", "〜よりむしろ"],
  ["regardless of", "〜に関係なく"],
  ["report to work", "出勤する"],
  ["right away", "すぐに"],
  ["room and board", "部屋代と食費"],
  ["round-trip ticket", "往復切符"],
  ["run into", "偶然会う／ぶつかる"],
  ["set aside", "取っておく"],
  ["should you have any questions", "ご不明点がありましたら"],
  ["spare no expense", "費用を惜しまない"],
  ["speak highly of", "高く評価する"],
  ["stuck in traffic", "渋滞にはまって"],
  ["take advantage of", "活用する"],
  ["take effect", "施行される"],
  ["take place", "行われる"],
  ["thanks to", "〜のおかげで"],
  ["to whom it may concern", "関係者各位"],
  ["trade fair", "見本市"],
  ["until further notice", "追って通知があるまで"],
  ["upon request", "要請に応じて"],
  ["wear and tear", "摩耗"],
  ["well in advance", "十分前もって"],
  ["when it comes to", "〜に関して言えば"],
  ["with the exception of", "〜を除いて"],
  ["within walking distance", "徒歩圏内"],
  ["work ethic", "勤労倫理"]
];

function createWord(id) {
  const [en, ja] = seedWords[(id - 1) % seedWords.length];
  return {
    id,
    q: `${en} #${id}`,
    a: `${ja}${id}`
  };
}

export const WORDS = Array.from({ length: 1477 }, (_, i) => createWord(i + 1));
